services:

  geoserver:
    image: docker.osgeo.org/geoserver:2.27.x
    # restart: unless-stopped
    ports:
      - 8088:8080
    volumes:
      - type: bind
        source: ./montages/geoserver/data
        #target: /opt/geoserver_data
        target: /usr/local/tomcat/webapps/geoserver/data
    environment:
      RECREATE_DATADIR: "false"
      CORS_ENABLED: "true"

  iipsrv:
    # build:
    #   context: iipsrv
    #   dockerfile: Dockerfile
    image: iipsrv/iipsrv
    # restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./montages/images:/images:ro
    environment:
      MAX_LAYERS: "-1"
      CORS: "*"

  mtd:
    image: php:8.2-apache
    # restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./montages/mtd:/var/www/html/:ro
    environment:
      CORS: "*"

  img:
    image: php:8.2-apache
    # restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./montages/images:/var/www/html/:ro
    environment:
      CORS: "*"
      
