services:

  geoserver:
    image: docker.osgeo.org/geoserver:2.27.x
    # restart: unless-stopped
    ports:
      - 8088:8080
    volumes:
      - type: bind
        source: ./montages/geoserver/data
        #target: /opt/geoserver_data
        target: /usr/local/tomcat/webapps/geoserver/data
    environment:
      RECREATE_DATADIR: "false"
      CORS_ENABLED: "true"

  iipsrv:
    # build:
    #   context: iipsrv
    #   dockerfile: Dockerfile
    image: iipsrv/iipsrv
    # restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./montages/images:/images:ro
    environment:
      MAX_LAYERS: "-1"
      CORS: "*"

  mtd:
    image: nginx
    # restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./montages/mtd:/usr/share/nginx/html/:ro
      - ./montages/default.conf:/etc/nginx/conf.d/default.conf:ro

  img:
    image: nginx
    # restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./montages/images:/usr/share/nginx/html/:ro
      - ./montages/default.conf:/etc/nginx/conf.d/default.conf:ro

  reverse:
    image: nginx
    # restart: unless-stopped
    userns_mode: "host"
    network_mode: host
    #ports:
    #  - "8888:80"
    volumes:
      - ./montages/reverse.conf:/etc/nginx/conf.d/default.conf:ro
      - ./montages/proxy_params:/etc/nginx/proxy_params:ro
